export const NOVA_CONFIG = {
  MAX_ENERGY: 100,
  ACTIVATION_COST: 100,
  DURATION_TURNS: 5,
  SCORE_MULTIPLIER: 2,
  NOVA_CLEAR_MIN_LINES: 2,
  NOVA_CLEAR_BONUS: 50,
  PRISM_CLEAR_BONUS: 50,

  ENERGY_REWARDS: {
    PIECE_PLACEMENT: 2,
    LINE_CLEAR_PER_LINE: 8,
    COMBO_2: 5,
    COMBO_3: 8,
    COMBO_4_PLUS: 12,
  },
};
